/**
 * Configuration for all 52 tabular parameters
 * Defines bounds, defaults, labels, and groupings for the parameter panel
 */

import { ParameterGroup, type TabularParameter } from './tabular.types';

/**
 * Complete configuration array for all tabular parameters
 * Organized by parameter groups for logical UI presentation
 */
export const TABULAR_PARAMETERS: TabularParameter[] = [
	// ==================== TRANSIT GROUP ====================
	{
		name: 'pl_trandep',
		label: 'Transit Depth',
		description:
			'The depth of the planetary transit in parts per million (ppm)',
		min: 0,
		max: 100000,
		step: 100,
		defaultValue: 5000,
		unit: 'ppm',
		group: ParameterGroup.TRANSIT,
	},
	{
		name: 'pl_trandep_frac',
		label: 'Transit Depth Fraction',
		description: 'The fractional transit depth (dimensionless)',
		min: 0,
		max: 0.1,
		step: 0.0001,
		defaultValue: 0.005,
		unit: '',
		group: ParameterGroup.TRANSIT,
	},
	{
		name: 'pl_trandeperr1',
		label: 'Transit Depth Error (+)',
		description: 'Upper uncertainty in transit depth',
		min: 0,
		max: 10000,
		step: 10,
		defaultValue: 100,
		unit: 'ppm',
		group: ParameterGroup.TRANSIT,
	},
	{
		name: 'pl_trandeperr2',
		label: 'Transit Depth Error (-)',
		description: 'Lower uncertainty in transit depth',
		min: -10000,
		max: 0,
		step: 10,
		defaultValue: -100,
		unit: 'ppm',
		group: ParameterGroup.TRANSIT,
	},

	// ==================== DURATION GROUP ====================
	{
		name: 'pl_trandur',
		label: 'Transit Duration',
		description: 'Duration of the planetary transit',
		min: 0,
		max: 24,
		step: 0.01,
		defaultValue: 3.5,
		unit: 'hours',
		group: ParameterGroup.DURATION,
	},
	{
		name: 'pl_trandurerr1',
		label: 'Transit Duration Error (+)',
		description: 'Upper uncertainty in transit duration',
		min: 0,
		max: 5,
		step: 0.01,
		defaultValue: 0.1,
		unit: 'hours',
		group: ParameterGroup.DURATION,
	},
	{
		name: 'pl_trandurerr2',
		label: 'Transit Duration Error (-)',
		description: 'Lower uncertainty in transit duration',
		min: -5,
		max: 0,
		step: 0.01,
		defaultValue: -0.1,
		unit: 'hours',
		group: ParameterGroup.DURATION,
	},

	// ==================== ORBITAL GROUP ====================
	{
		name: 'pl_orbper',
		label: 'Orbital Period',
		description: 'Time for one complete orbit around the host star',
		min: 0.1,
		max: 5000,
		step: 0.1,
		defaultValue: 10,
		unit: 'days',
		group: ParameterGroup.ORBITAL,
	},
	{
		name: 'pl_orbpererr1',
		label: 'Orbital Period Error (+)',
		description: 'Upper uncertainty in orbital period',
		min: 0,
		max: 100,
		step: 0.001,
		defaultValue: 0.01,
		unit: 'days',
		group: ParameterGroup.ORBITAL,
	},
	{
		name: 'pl_orbpererr2',
		label: 'Orbital Period Error (-)',
		description: 'Lower uncertainty in orbital period',
		min: -100,
		max: 0,
		step: 0.001,
		defaultValue: -0.01,
		unit: 'days',
		group: ParameterGroup.ORBITAL,
	},

	// ==================== RATIO GROUP ====================
	{
		name: 'pl_ratror',
		label: 'Planet-Star Radius Ratio',
		description: 'Ratio of planet radius to stellar radius',
		min: 0,
		max: 0.5,
		step: 0.001,
		defaultValue: 0.1,
		unit: '',
		group: ParameterGroup.RATIO,
	},
	{
		name: 'pl_ratrorerr1',
		label: 'Radius Ratio Error (+)',
		description: 'Upper uncertainty in planet-star radius ratio',
		min: 0,
		max: 0.1,
		step: 0.0001,
		defaultValue: 0.005,
		unit: '',
		group: ParameterGroup.RATIO,
	},
	{
		name: 'pl_ratrorerr2',
		label: 'Radius Ratio Error (-)',
		description: 'Lower uncertainty in planet-star radius ratio',
		min: -0.1,
		max: 0,
		step: 0.0001,
		defaultValue: -0.005,
		unit: '',
		group: ParameterGroup.RATIO,
	},

	// ==================== PHOTOMETRY GROUP ====================
	{
		name: 'st_tmag',
		label: 'TESS Magnitude',
		description: 'Stellar magnitude in TESS bandpass',
		min: 0,
		max: 20,
		step: 0.01,
		defaultValue: 10,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_gaiamag',
		label: 'Gaia Magnitude',
		description: 'Stellar magnitude in Gaia G band',
		min: 0,
		max: 25,
		step: 0.01,
		defaultValue: 12,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_kmag',
		label: 'K Magnitude',
		description: 'Stellar magnitude in K band (2MASS)',
		min: 0,
		max: 20,
		step: 0.01,
		defaultValue: 9,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_jmag',
		label: 'J Magnitude',
		description: 'Stellar magnitude in J band (2MASS)',
		min: 0,
		max: 20,
		step: 0.01,
		defaultValue: 10,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_hmag',
		label: 'H Magnitude',
		description: 'Stellar magnitude in H band (2MASS)',
		min: 0,
		max: 20,
		step: 0.01,
		defaultValue: 9.5,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_vmag',
		label: 'V Magnitude',
		description: 'Stellar magnitude in V band (Johnson)',
		min: 0,
		max: 25,
		step: 0.01,
		defaultValue: 11,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_bmag',
		label: 'B Magnitude',
		description: 'Stellar magnitude in B band (Johnson)',
		min: 0,
		max: 25,
		step: 0.01,
		defaultValue: 11.5,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_w1mag',
		label: 'WISE W1 Magnitude',
		description: 'Stellar magnitude in WISE W1 band (3.4 μm)',
		min: 0,
		max: 20,
		step: 0.01,
		defaultValue: 8.5,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},
	{
		name: 'sy_w2mag',
		label: 'WISE W2 Magnitude',
		description: 'Stellar magnitude in WISE W2 band (4.6 μm)',
		min: 0,
		max: 20,
		step: 0.01,
		defaultValue: 8.5,
		unit: 'mag',
		group: ParameterGroup.PHOTOMETRY,
	},

	// ==================== ASTROMETRY GROUP ====================
	{
		name: 'sy_dist',
		label: 'Distance',
		description: 'Distance to the stellar system',
		min: 0,
		max: 10000,
		step: 1,
		defaultValue: 100,
		unit: 'pc',
		group: ParameterGroup.ASTROMETRY,
	},
	{
		name: 'sy_plx',
		label: 'Parallax',
		description: 'Stellar parallax measurement',
		min: 0,
		max: 1000,
		step: 0.1,
		defaultValue: 10,
		unit: 'mas',
		group: ParameterGroup.ASTROMETRY,
	},
	{
		name: 'sy_pm',
		label: 'Proper Motion',
		description: 'Total proper motion',
		min: 0,
		max: 10000,
		step: 1,
		defaultValue: 50,
		unit: 'mas/yr',
		group: ParameterGroup.ASTROMETRY,
	},
	{
		name: 'sy_pmra',
		label: 'Proper Motion RA',
		description: 'Proper motion in right ascension',
		min: -10000,
		max: 10000,
		step: 1,
		defaultValue: 0,
		unit: 'mas/yr',
		group: ParameterGroup.ASTROMETRY,
	},
	{
		name: 'sy_pmdec',
		label: 'Proper Motion Dec',
		description: 'Proper motion in declination',
		min: -10000,
		max: 10000,
		step: 1,
		defaultValue: 0,
		unit: 'mas/yr',
		group: ParameterGroup.ASTROMETRY,
	},

	// ==================== STELLAR GROUP ====================
	{
		name: 'st_rad',
		label: 'Stellar Radius',
		description: 'Radius of the host star',
		min: 0.1,
		max: 100,
		step: 0.01,
		defaultValue: 1,
		unit: 'R☉',
		group: ParameterGroup.STELLAR,
	},
	{
		name: 'st_teff',
		label: 'Effective Temperature',
		description: 'Stellar effective temperature',
		min: 2000,
		max: 50000,
		step: 10,
		defaultValue: 5778,
		unit: 'K',
		group: ParameterGroup.STELLAR,
	},
	{
		name: 'st_mass',
		label: 'Stellar Mass',
		description: 'Mass of the host star',
		min: 0.1,
		max: 100,
		step: 0.01,
		defaultValue: 1,
		unit: 'M☉',
		group: ParameterGroup.STELLAR,
	},
	{
		name: 'st_logg',
		label: 'Surface Gravity',
		description: 'Logarithm of stellar surface gravity',
		min: 0,
		max: 5,
		step: 0.01,
		defaultValue: 4.44,
		unit: 'log(cm/s²)',
		group: ParameterGroup.STELLAR,
	},
	{
		name: 'st_dens',
		label: 'Stellar Density',
		description: 'Average density of the host star',
		min: 0.001,
		max: 100,
		step: 0.01,
		defaultValue: 1.41,
		unit: 'g/cm³',
		group: ParameterGroup.STELLAR,
	},
	{
		name: 'st_vsin',
		label: 'Rotational Velocity',
		description: 'Projected stellar rotational velocity',
		min: 0,
		max: 500,
		step: 0.1,
		defaultValue: 2,
		unit: 'km/s',
		group: ParameterGroup.STELLAR,
	},
	{
		name: 'st_met',
		label: 'Metallicity',
		description: 'Stellar metallicity [Fe/H]',
		min: -5,
		max: 1,
		step: 0.01,
		defaultValue: 0,
		unit: 'dex',
		group: ParameterGroup.STELLAR,
	},

	// ==================== OBSERVATIONS GROUP ====================
	{
		name: 'st_nphot',
		label: 'Photometric Observations',
		description: 'Number of photometric time series',
		min: 0,
		max: 100,
		step: 1,
		defaultValue: 1,
		unit: '',
		group: ParameterGroup.OBSERVATIONS,
	},
	{
		name: 'st_nrvc',
		label: 'Radial Velocity Observations',
		description: 'Number of radial velocity time series',
		min: 0,
		max: 100,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.OBSERVATIONS,
	},
	{
		name: 'pl_ntranspec',
		label: 'Transit Spectra',
		description: 'Number of transit spectra',
		min: 0,
		max: 50,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.OBSERVATIONS,
	},
	{
		name: 'pl_nespec',
		label: 'Eclipse Spectra',
		description: 'Number of eclipse spectra',
		min: 0,
		max: 50,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.OBSERVATIONS,
	},
	{
		name: 'pl_ndispec',
		label: 'Direct Imaging Spectra',
		description: 'Number of direct imaging spectra',
		min: 0,
		max: 50,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.OBSERVATIONS,
	},
	{
		name: 'st_nspec',
		label: 'Stellar Spectra',
		description: 'Number of stellar spectra measurements',
		min: 0,
		max: 100,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.OBSERVATIONS,
	},

	// ==================== DERIVED GROUP ====================
	{
		name: 'R_p_est_Rearth',
		label: 'Planet Radius (Earth)',
		description: 'Estimated planet radius in Earth radii',
		min: 0.1,
		max: 50,
		step: 0.1,
		defaultValue: 1,
		unit: 'R⊕',
		group: ParameterGroup.DERIVED,
	},
	{
		name: 'duty_cycle',
		label: 'Duty Cycle',
		description: 'Fraction of orbit spent in transit',
		min: 0,
		max: 0.5,
		step: 0.001,
		defaultValue: 0.05,
		unit: '',
		group: ParameterGroup.DERIVED,
	},
	{
		name: 'B_minus_V',
		label: 'B-V Color Index',
		description: 'B minus V magnitude (color indicator)',
		min: -0.5,
		max: 2.5,
		step: 0.01,
		defaultValue: 0.65,
		unit: 'mag',
		group: ParameterGroup.DERIVED,
	},
	{
		name: 'J_minus_K',
		label: 'J-K Color Index',
		description: 'J minus K magnitude (color indicator)',
		min: -0.5,
		max: 2,
		step: 0.01,
		defaultValue: 0.5,
		unit: 'mag',
		group: ParameterGroup.DERIVED,
	},
	{
		name: 'M_TESS',
		label: 'TESS Absolute Magnitude',
		description: 'Absolute magnitude in TESS band',
		min: -10,
		max: 20,
		step: 0.01,
		defaultValue: 5,
		unit: 'mag',
		group: ParameterGroup.DERIVED,
	},
	{
		name: 'depth_vs_noise',
		label: 'Depth-to-Noise Ratio',
		description: 'Transit depth divided by photometric noise',
		min: 0,
		max: 1000,
		step: 0.1,
		defaultValue: 10,
		unit: '',
		group: ParameterGroup.DERIVED,
	},
	{
		name: 'rho_star_from_transit',
		label: 'Stellar Density (Transit)',
		description: 'Stellar density derived from transit parameters',
		min: 0.001,
		max: 100,
		step: 0.01,
		defaultValue: 1.41,
		unit: 'g/cm³',
		group: ParameterGroup.DERIVED,
	},

	// ==================== FLAGS GROUP ====================
	{
		name: 'ttv_flag',
		label: 'TTV Flag',
		description: 'Transit timing variation flag (0 or 1)',
		min: 0,
		max: 1,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.FLAGS,
	},
	{
		name: 'tran_flag',
		label: 'Transit Flag',
		description: 'Transiting planet flag (0 or 1)',
		min: 0,
		max: 1,
		step: 1,
		defaultValue: 1,
		unit: '',
		group: ParameterGroup.FLAGS,
	},
	{
		name: 'rv_flag',
		label: 'RV Flag',
		description: 'Radial velocity detection flag (0 or 1)',
		min: 0,
		max: 1,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.FLAGS,
	},
	{
		name: 'cb_flag',
		label: 'Circumbinary Flag',
		description: 'Circumbinary planet flag (0 or 1)',
		min: 0,
		max: 1,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.FLAGS,
	},
	{
		name: 'pl_controv_flag',
		label: 'Controversial Flag',
		description: 'Controversial planet flag (0 or 1)',
		min: 0,
		max: 1,
		step: 1,
		defaultValue: 0,
		unit: '',
		group: ParameterGroup.FLAGS,
	},
	{
		name: 'pl_imppar',
		label: 'Impact Parameter',
		description: 'Impact parameter of transit (0-1)',
		min: 0,
		max: 1,
		step: 0.01,
		defaultValue: 0.5,
		unit: '',
		group: ParameterGroup.FLAGS,
	},
	{
		name: 'pl_tranmid',
		label: 'Transit Midpoint',
		description: 'Transit midpoint time (BJD)',
		min: 2450000,
		max: 2500000,
		step: 0.001,
		defaultValue: 2458000,
		unit: 'BJD',
		group: ParameterGroup.FLAGS,
	},
];

/**
 * Helper function to get default values for all parameters
 * Used for form initialization
 */
export function getDefaultValues(): Record<string, number> {
	return TABULAR_PARAMETERS.reduce(
		(acc, param) => {
			acc[param.name] = param.defaultValue;
			return acc;
		},
		{} as Record<string, number>,
	);
}

/**
 * Helper function to group parameters by their group type
 * Returns a map of group -> parameters array
 */
export function getGroupedParameters(): Map<
	ParameterGroup,
	TabularParameter[]
> {
	const grouped = new Map<ParameterGroup, TabularParameter[]>();

	for (const param of TABULAR_PARAMETERS) {
		const existing = grouped.get(param.group);
		if (existing) {
			existing.push(param);
		} else {
			grouped.set(param.group, [param]);
		}
	}

	return grouped;
}

/**
 * Human-readable labels for parameter groups
 * Used for UI display in accordion headers
 */
export const PARAMETER_GROUP_LABELS: Record<ParameterGroup, string> = {
	[ParameterGroup.TRANSIT]: 'Transit Depth Parameters',
	[ParameterGroup.DURATION]: 'Transit Duration Parameters',
	[ParameterGroup.ORBITAL]: 'Orbital Period Parameters',
	[ParameterGroup.RATIO]: 'Planet-Star Ratio Parameters',
	[ParameterGroup.PHOTOMETRY]: 'Photometry & Magnitudes',
	[ParameterGroup.ASTROMETRY]: 'Astrometry & Distance',
	[ParameterGroup.STELLAR]: 'Stellar Properties',
	[ParameterGroup.OBSERVATIONS]: 'Observation Counts',
	[ParameterGroup.DERIVED]: 'Derived Parameters',
	[ParameterGroup.FLAGS]: 'Flags & Metadata',
};
